FROM rabbitmq:3-management
# EXPOSE 15672 5672
# ADD init.sh /init.sh

# Makes the NODENAME static
# RUN echo 'NODENAME=rabbit@localhost' > /etc/rabbitmq/rabbitmq-env.conf 

# Define default command
# CMD ["./init.sh"]